title: "What Factors Contribute to Surviving on a Sinking Ship - A Deep Dive into the Titanic"
author: "Alan Powichrowski, Karan Khubdikar, Sam Fo, Sampson Yu"
date: "2023-12-01"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force 
bibtex_bibfiles:
    - references.bib