name: '522_group4_M1'
channels:
    - defaults
    - conda-forge
    - r
dependencies:
    - python=3.11.6
    - pip=23.3.1
    - ipykernel=6.26
    - nb_conda_kernels=2.3.1
    - panel
    - r-base=4.3
    - r-essentials
    - r-devtools
    - r-gert
    - r-usethis
    - r-testthat
    - r-startup
    - r-rmarkdown
    - r-stringi
    - r-tidyverse
    - r-hmisc
    - r-rjson
    - r-ggally
    - r-ggthemes
    - r-cowplot
    - r-irkernel
    - r-titanic #Titanic Data
    - r-knitr
    - r-gridExtra
    - r-dplyr
    - jupyter-book=0.15.1
    - ipython=8.15.0
    - notebook=7.0.6
    - r-docopt
    - r-png
    - r-grid
 

